---
apiVersion: v1
kind: Pod
metadata:
  labels:
    foo: bar
  name: pod-bar
  namespace: crossplane-system
spec:
  containers:
  - image: registry.k8s.io/pause
    name: pod-bar

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    foo: bar
  name: pod-foo
  namespace: crossplane-system
spec:
  containers:
  - image: registry.k8s.io/pause
    name: pod-foo
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ObservedObjectCollection
metadata:
  name: foo-collection
spec:
  observeObjects:
    apiVersion: v1
    kind: Pod
    selector:
      matchLabels:
        foo: bar
  objectTemplate:
    metadata:
      labels:
        l1: v1
      annotations:
        a1: v1
  providerConfigRef:
    name: kubernetes-provider
