---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: foo
spec:
  # Use management policy ObserveCreateUpdate to observe, create, or update k8s
  # resource, but leave to third party to delete the resource
  managementPolicy: ObserveCreateUpdate
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        # name in manifest is optional and defaults to Object name
        # name: some-other-name
        namespace: default
      data:
        sample-key: sample-value
  providerConfigRef:
    name: kubernetes-provider
