---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
data:
  sample-key: sample-value
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: foo
spec:
  # Use management policy ObserveDelete to observe or delete k8s resource,
  # but leave to third party to create or update the resource
  managementPolicy: ObserveDelete
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        # name in manifest is optional and defaults to Object name
        # name: some-other-name
        namespace: default
  providerConfigRef:
    name: kubernetes-provider
