#apiVersion: v1
#kind: Secret
#metadata:
#  namespace: crossplane-system
#  name: example-provider-secret
#type: Opaque
#data:
  # credentials: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: kubernetes.m.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: kubernetes-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: cluster-config
      key: kubeconfig
