//go:build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObserveObjectCriteria) DeepCopyInto(out *ObserveObjectCriteria) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObserveObjectCriteria.
func (in *ObserveObjectCriteria) DeepCopy() *ObserveObjectCriteria {
	if in == nil {
		return nil
	}
	out := new(ObserveObjectCriteria)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedObjectCollection) DeepCopyInto(out *ObservedObjectCollection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedObjectCollection.
func (in *ObservedObjectCollection) DeepCopy() *ObservedObjectCollection {
	if in == nil {
		return nil
	}
	out := new(ObservedObjectCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObservedObjectCollection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedObjectCollectionList) DeepCopyInto(out *ObservedObjectCollectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObservedObjectCollection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedObjectCollectionList.
func (in *ObservedObjectCollectionList) DeepCopy() *ObservedObjectCollectionList {
	if in == nil {
		return nil
	}
	out := new(ObservedObjectCollectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObservedObjectCollectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedObjectCollectionSpec) DeepCopyInto(out *ObservedObjectCollectionSpec) {
	*out = *in
	in.ObserveObjects.DeepCopyInto(&out.ObserveObjects)
	in.ProviderConfigReference.DeepCopyInto(&out.ProviderConfigReference)
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(ObservedObjectTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedObjectCollectionSpec.
func (in *ObservedObjectCollectionSpec) DeepCopy() *ObservedObjectCollectionSpec {
	if in == nil {
		return nil
	}
	out := new(ObservedObjectCollectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedObjectCollectionStatus) DeepCopyInto(out *ObservedObjectCollectionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	if in.MembershipLabel != nil {
		in, out := &in.MembershipLabel, &out.MembershipLabel
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedObjectCollectionStatus.
func (in *ObservedObjectCollectionStatus) DeepCopy() *ObservedObjectCollectionStatus {
	if in == nil {
		return nil
	}
	out := new(ObservedObjectCollectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedObjectReference) DeepCopyInto(out *ObservedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedObjectReference.
func (in *ObservedObjectReference) DeepCopy() *ObservedObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObservedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedObjectTemplate) DeepCopyInto(out *ObservedObjectTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedObjectTemplate.
func (in *ObservedObjectTemplate) DeepCopy() *ObservedObjectTemplate {
	if in == nil {
		return nil
	}
	out := new(ObservedObjectTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedObjectTemplateMetadata) DeepCopyInto(out *ObservedObjectTemplateMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedObjectTemplateMetadata.
func (in *ObservedObjectTemplateMetadata) DeepCopy() *ObservedObjectTemplateMetadata {
	if in == nil {
		return nil
	}
	out := new(ObservedObjectTemplateMetadata)
	in.DeepCopyInto(out)
	return out
}
